name: make

on:
  workflow_call:
    inputs:
      release:
        default: false
        required: false
        type: boolean
      upload:
        default: false
        required: false
        type: boolean

env:
  TEA_SECRET: ${{ secrets.TEA_SECRET }}

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: | # Use on-box make until tea/pantry revlock is resolved
        sudo apt-get install \
          texlive-latex-base \
          texlive-fonts-recommended \
          texlive-fonts-extra
        brew install \
          pandoc \
          pandoc-crossref \
          librsvg
        #FIXME: Can't pass secrets to remote-branch CI, so this is until teaxyz/pantry is public
        sed -ne 's/^# tea\/white-paper \([0-9]*\.[0-9]*\.[0-9]*\)/VERSION=\1/p' README.md >> $GITHUB_ENV
    - run: |
        # Need a standard font, and ttf-mscorefonts-installer has a EULA dialog. Definitely #FIXME
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
        sudo apt-get install texlive texlive-latex-extra texlive-xetex msttcorefonts #FIXME
    # - run: .github/mk-pantry-accessible.sh ${{ secrets.TEMP_JACOBS_GITHUB_PAT }}
    # - uses: teaxyz/setup@v0

    - name: Set Version - Release
      if: ${{ inputs.release }}
      run: echo "- \fancyfoot[L]{$VERSION}" >> metadata.yml
    - name: Set Version - CI/CD
      if: ${{ !inputs.release }}
      run: |
        date=$(date '+%Y%m%d')
        echo "- \fancyfoot[L]{$VERSION+$date}" >> metadata.yml

    # - run: tea make
    - run: make  # Use on-box make until tea/pantry revlock is resolved
    - uses: actions/upload-artifact@v3
      with:
        name: tea.white-paper
        path: |
          tea.white-paper.pdf
          tea.white-paper_??.pdf

    # Following steps only run for upload: true
    - name: AWS credentials
      if: ${{ inputs.upload }}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Bundle translations
      if: ${{ inputs.upload }}
      run: |
        mkdir white-papers
        cp tea.white-paper_??.pdf white-papers/
    - name: Bundle release
      if: ${{ inputs.upload && inputs.release }}
      run: cp tea.white-paper.pdf white-papers/

    - name: Upload to S3
      if: ${{ inputs.upload }}
      run: |
        aws s3 sync \
          ./white-papers s3://www.tea.xyz/ \
          --metadata-directive REPLACE \
          --cache-control no-cache,must-revalidate
    - name: Invalidate cache
      if: ${{ inputs.upload }}
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.AWS_CF_DISTRIBUTION_ID }} \
          --paths / /tea.white-paper*.pdf
